
// Generated by https://quicktype.io

export interface ReqResUserCourseActivity {
    count:   number;
    results: ResultUserCourseActivity[];
}

export interface ResultUserCourseActivity {
    user_name:                    string;
    user_surname:                 string;
    user_email:                   string;
    user_role:                    string;
    course_id:                    number;
    course_title:                 string;
    course_category:              string;
    course_duration:              number;
    completion_ratio:             number;
    num_video_consumed_minutes:   number;
    course_enroll_date:           string;
    course_start_date:            string;
    course_completion_date:       null | string;
    course_first_completion_date: null | string;
    course_last_accessed_date:    string;
    user_is_deactivated:          boolean;
}

 // Generated by https://quicktype.io

export interface FectAllUserResponse {
    count:   number;
    next:    string;
    results: Result[];
}

export interface Result {
    user_name:                string;
    user_surname:             string;
    user_email:               string;
    user_joined_date:          string;
    num_completed_courses?: any     ;
    num_video_consumed_minutes: number;
    last_date_visit:           string;
}


export interface FetchAllCoursesActivity {
    count:   number;
    results: ResultCourses[];
}

export interface ResultCourses {
    user_name:                    string;
    user_surname:                 string;
    user_email:                   string;
    //user_role:                    string;
   // course_id:                    number;
    course_title:                 string;
    //course_category:              string;
    //course_duration:              number;
    completion_ratio?:             number;
    num_video_consumed_minutes:   number;
    course_enroll_date?:           string;
    course_start_date?:            string;
    course_completion_date?:       string;
    course_first_completion_date?: string;
    course_last_accessed_date?:    string;
}