
 // Generated by https://quicktype.io

export interface FectAllUserResponse {
    count:   number;
    next:    string;
    results: Result[];
}

export interface Result {
    id:                      number;
    user_name:                string;
    user_surname:             string;
    user_email:               string;
    user_joined_date:          string;
    num_video_consumed_minutes: number;
    last_date_visit:           string;
}

