
 // Generated by https://quicktype.io

export interface FectAllUserResponse {
    count:   number;
    next:    string;
    results: Result[];
}

export interface Result {
    id:                      number;
    userName:                string;
    userSurname:             string;
    userEmail:               string;
    userJoinedDate:          string;
    numVideoConsumedMinutes: number;
    lastDateVisit:           string;
}

